version: "3.8"
services:
  dev:
    container_name: ${APP}-dev
    restart: always
    build:
      context: "."
      dockerfile: ./docker/Dockerfile.dev
      args:
        - PORT=${PORT}
        - APP=${APP}
    volumes:
      - ./:/usr/local/apps/${APP}:delegated
      - ignore:/usr/local/apps/${APP}/node_modules
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

volumes:
  ignore:
