version: "3.8"
services:
  web:
    container_name: ${WEBSERVER_DIR}
    restart: always
    build:
      context: "."
      dockerfile: ./docker/Dockerfile.dev
      args:
        - PORT=${PORT}
        - WEBSERVER_DIR=${WEBSERVER_DIR}
    volumes:
      - ./:/usr/local/apps/${WEBSERVER_DIR}:delegated
      - ignore:/usr/local/apps/${WEBSERVER_DIR}/node_modules
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    env_file:
      - .env

volumes:
  ignore:
