FROM node:gallium-alpine

ARG WEBSERVER_DIR=${WEBSERVER_DIR}
WORKDIR /usr/local/apps/${WEBSERVER_DIR}

COPY . .

RUN yarn

ENV PATH=/usr/local/apps/${WEBSERVER_DIR}/node_modules/.bin:$PATH

EXPOSE ${PORT}

CMD ["yarn", "run", "start"]
